version: '3'

services:
  node-red:
    image: nodered/node-red
    ports:
      - "1880:1880"
    volumes:
      - ./node-red:/data
    restart: always

  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_DB: mydb
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: password
      INFLUXDB_USER: user
      INFLUXDB_USER_PASSWORD: userpassword
    volumes:
      - ./influxdb:/var/lib/influxdb
    restart: always

  chronograf:
    image: chronograf:latest
    ports:
      - "8888:8888"
    environment:
      CHRONOGRAF_DB: http://influxdb:8086
    restart: always
